
# Exception

# def check_positive(number):
#     if number < 0:
#         raise ValueError("Negative numbers are not Allowed!")
    

# try:
#     print(check_positive(5)) 
# except ValueError as e:
#     print(e)


# try :
#     result = 10/0
# except ZeroDivisionError:
#     print("oops! you cant divide by zero,") 
