
# Exception

# def check_positive(number):
#     if number < 0:
#         raise ValueError("Negative numbers are not Allowed!")
    

# try:
#     print(check_positive(5)) 
# except ValueError as e:
#     print(e)


# try :
#     result = 10/0
# except ZeroDivisionError:
#     print("oops! you cant divide by zero,") 

# finally-clause

# try :
#     file = open("example.txt","r")
#     # some kind of code raise an exception 

# except FileNotFoundError:
#     print("file not found!")

# finally:
#     file.close()
#     print("file closed")

# try:
#     num1 = float(input("enter the 1st number: "))
#     num2 = float(input("enter the 2nd number: "))
#     result = num1 /num2
#     print(f"the result is : {result}")

# except FileNotFoundError:
#     print("File not found!")

# except ZeroDivisionError:
#    print("oops! you cant divide by zero,")      


 



